### ISSUE TITLE
Errors with Theme Check

### ISSUE THREAD

**Issue by martinburdon** [ThemeFuse/Scratch-Theme#11]
Running Scratch through Theme Check is returning the following errors.

```
WARNING: Found a translation function that is missing a text-domain. Function _n_noop, with the arguments 'This theme requires the following plugin: %1$s.','This theme requires the following plugins: %1$s.'
WARNING: Found a translation function that is missing a text-domain. Function _n_noop, with the arguments 'This theme recommends the following plugin: %1$s.','This theme recommends the following plugins: %1$s.'
WARNING: Found a translation function that is missing a text-domain. Function _n_noop, with the arguments 'The following required plugin is currently inactive: %1$s.','The following required plugins are currently inactive: %1$s.'
WARNING: Found a translation function that is missing a text-domain. Function _n_noop, with the arguments 'The following recommended plugin is currently inactive: %1$s.','The following recommended plugins are currently inactive: %1$s.'
WARNING: Found a translation function that is missing a text-domain. Function _n_noop, with the arguments 'The following plugin needs to be updated to its latest version to ensure maximum compatibility with this theme: %1$s.','The following plugins need to be updated to their latest version to ensure maximum compatibility with this theme: %1$s.'
WARNING: Found a translation function that is missing a text-domain. Function _n_noop, with the arguments 'Sorry, but you do not have the correct permissions to update the %s plugin. Contact the administrator of this site for help on getting the plugin updated.','Sorry, but you do not have the correct permissions to update the %s plugins. Contact the administrator of this site for help on getting the plugins updated.'
WARNING: Found a translation function that is missing a text-domain. Function _n_noop, with the arguments 'Sorry, but you do not have the correct permissions to install the %s plugin. Contact the administrator of this site for help on getting the plugin installed.','Sorry, but you do not have the correct permissions to install the %s plugins. Contact the administrator of this site for help on getting the plugins installed.'
WARNING: Found a translation function that is missing a text-domain. Function _n_noop, with the arguments 'Sorry, but you do not have the correct permissions to activate the %s plugin. Contact the administrator of this site for help on getting the plugin activated.','Sorry, but you do not have the correct permissions to activate the %s plugins. Contact the administrator of this site for help on getting the plugins activated.'
WARNING: Found a translation function that is missing a text-domain. Function _n_noop, with the arguments 'Begin installing plugin','Begin installing plugins'
WARNING: Found a translation function that is missing a text-domain. Function _n_noop, with the arguments 'Begin activating plugin','Begin activating plugins'
WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments '%s says:'
```

Cheers

**Comment by moldcraft** [comment]
I can't find where this comes from

```
WARNING: Found a translation function that is missing a text-domain. Function __, with the arguments '%s says:'
```

**Comment by martinburdon** [comment]
Sorry to bring this issue back up - I'm still getting this whilst using it in a theme I'm developing for ThemeForest. I'm getting close to submitting the theme, are you aware of themes being rejected due to this issue which seems to be something to do with the TGM Plugin Activation script?

**Comment by 2Fwebd** [comment]
HI, 

Yes it's caused by the TGM class, don't know why it was working great and since a few weeks Theme Check is throwing errors about it ... Anyway just just have to make small updates on the TGM class : 
![class-tgm-plugin-activation_php_-_alka_root](https://cloud.githubusercontent.com/assets/5446124/10270259/68490240-6aec-11e5-944b-03a3b78fff22.jpg)

It's the same for all the missing ones, I hope that helps!

Cheers,

2F

**Comment by martinburdon** [comment]
Thanks for the reply @2Fwebd – I already have the script set up this way however :worried: 

I've just noticed I'm also getting the following **Required** issue from Theme Check
`REQUIRED: TGM-Plugin-Activation/class-tgm-plugin-activation.php. Themes should use add_theme_page() for adding admin pages.
Line 646: $this->page_hook = call_user_func( 'add_{$type}_page', $args['parent_slug'], $args['page_title'], $args['menu_t`

**Comment by duongancol** [comment]
@martinburdon : make sure you're using the latest version of TGM plugin and don't worry about any issues with theme check. Because the reviewer will ignore all issues that releated to 3rd-plugin. It's my experience

**Comment by martinburdon** [comment]
Thanks for your reply @duongancol
I was hoping this would be the case however I've read a few posts on the TF forums (typically I can't find them now) where themes have been rejected due to code from 3rd party plugins as they're still part of your theme.

**Comment by duongancol** [comment]
if you have been rejected because code from TGM plugin, you just need to give them some explanation words in 'message' box. But it's very rare
