### ISSUE TITLE
remove_filter() in child theme

### ISSUE THREAD

**Issue by pe6o** [ThemeFuse/Scratch-Theme#13]
What is the best way to `remove_filter()` (in child theme) that is written in **inc/hooks.php**?

What I have to write in **the child-theme/functions.php**?
I can't seem to be able to do so...

Thanks!

**Comment by moldcraft** [comment]
If that filter is executed/applied later than `fw_init`, then try

```php
function _action_child_remove_hooks() {
    remove_filter(...);
}
add_action('fw_init', '_action_child_remove_hooks');
```
