### ISSUE TITLE
Styling Feature Preview does not work with the scratch theme

### ISSUE THREAD

**Issue by kyle-jennings** [ThemeFuse/Scratch-Theme#14]
While Parent both Child themes display the styling feature, the preview does not seem to work.

I am using WordPress 4.3.1, and have tried to use the theme with both a normal/standard install and the Multisite install.

Here is a screenshot of what I am seeing:

<img width="1083" alt="screen shot 2015-12-01 at 11 50 12 am" src="https://cloud.githubusercontent.com/assets/581351/11507394/d5fa6fce-9821-11e5-8aec-0f0e2c69a5c0.png">

Saving the settings however does seem to work, the new styles are applied to the site.

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/874
