### ISSUE TITLE
missing the style.css stylesheet

### ISSUE THREAD

**Issue by viper949** [ThemeFuse/Scratch-Theme#15]
Unpacking the package…

Installing the theme…

The package could not be installed. The theme is missing the style.css stylesheet.

Theme install failed.

**Comment by moldcraft** [comment]
Unyson is a plugin, not a theme

**Comment by viper949** [comment]
the scratch theme is a plugin???

**Comment by duongancol** [comment]
what is folder in your package?

**Comment by moldcraft** [comment]
Sorry, I thought it an issue on Unyson repository

**Comment by moldcraft** [comment]
The zip must contain

    theme-name/style.css

not

    theme-name/theme-name-parent/style.css

**Comment by viper949** [comment]
Ok I will double check this
