### ISSUE TITLE
Guide to include the framework directly in the theme

### ISSUE THREAD

**Issue by patilswapnilv** [ThemeFuse/Scratch-Theme#16]
Since the name says "from scratch", I was more of expecting a way to add the Unyson plugin directly into the theme directly as explained here http://manual.unyson.io/en/latest/

I tried adding the framework to a directory in the theme, and adding a function `_filter_fw_framework_plugin_directory_uri()` with the directory path. But after doing that I still get a notification in the dashboard saying "This theme needs Unyson plugin"

Also, I did not get the Unyson options as I get it when I install the plugin. Am I doing something wrong?

Is there a better way to do this. I don't want to ask the user to add the plugin, I rather want to add it to the theme files itself and activate it automatically when the theme is active. 

Also I would like to know if doing this, will make it difficult to maintain, with respect to keep the framework upto date in the theme always. Can I just make a git pull and roll out the update with theme update? Or again there is a better way to handle this?

**Comment by patilswapnilv** [comment]
Also is there a way to further strip it down and have my own version numbers? I would love to start with version: 0.0.1, but doing that with show update in the Dashboard.

**Comment by moldcraft** [comment]
> But after doing that I still get a notification in the dashboard saying "This theme needs Unyson plugin"

TGM is checking if a plugin named 'unyson' exists, if not, it will display notification. It doesn't have a way to detect if framework is loaded or not. So remove Unyson from TGM.

> Also, I did not get the Unyson options as I get it when I install the plugin

Where you did not get them?

> I don't want to ask the user to add the plugin, I rather want to add it to the theme files itself and activate it automatically when the theme is active.

ThemeForest doesn't allow that, you theme will not be accepted on marketplace. https://make.wordpress.org/themes/handbook/guidelines/plugin-territory/

> Also is there a way to further strip it down and have my own version numbers?

For Unyson, no.

**Comment by patilswapnilv** [comment]
I did not get the Unyson option in the Dashboard menu. When I add it directly to the theme file. But if themeforest does not allow it. There must be a good reason to avoid it. 

Though I am building this theme for person use. I would rather avoid it. 

Thanks,
