### ISSUE TITLE
portfolio shortcode

### ISSUE THREAD

**Issue by mrinal013** [ThemeFuse/Scratch-Theme#17]
Hello,

I am using Scratch-Theme and find out the working way with portfolio shortcode. In Scratch-Theme, there are no shortcode, by which I can try to edit. Would you please share the portfolio shorcode?

Thanks

**Comment by duongancol** [comment]
You could check out my 2 portfolio shortcode [here](https://www.dropbox.com/s/82wly51g92x2kso/portfolio-shortcode.zip?dl=0)
1st shortcode to get all portfolio 
the second have option to pick one by one.

**Comment by moldcraft** [comment]
Hello,

Try [this solution](https://wordpress.org/support/topic/filter-portfolio-items-by-categories-in-page-builders-gallery-portfolio?replies=3#post-7682966)
