### ISSUE TITLE
Adding a portfolio with multiple taxonomies

### ISSUE THREAD

**Issue by patilswapnilv** [ThemeFuse/Scratch-Theme#19]
I am looking for a solutions to have a **portfolio with multiple taxonomies(categories)**; 
Let me explain you, in this instance I need to showcase cloth, so I need to have taxonomies which can be utilized as one for each, like texture, color, washable/ non-washable , price etc. 

I know that can do that by adding additional taxonomies to any portfolio plugin; since all I need from the plugin is the skeleton code, for front-end, and the filters utilized (I will need to further enhance the filters of course.) But since I am using a scratch theme, I though may be I can make an extension, with using the existing portfolio extension as a base. 

I tried doing that, but could not find where you have declared the CPT and the taxonomies to it. 
Can you please help me with it? 

Also, can you please explain me what is a best way to provide additional extensions to existing Unyson extension's, so the end-user can activate/de-activate them like the once provided with the framework?

Please correct me if I am going wrong. Also any suggestion, of better ways to do this are most welcome. 

_Between, since I came across [Unyson](http://unyson.io/) this is one of my favorite things. Thanks for building it._

**Comment by moldcraft** [comment]
> but could not find where you have declared the CPT and the taxonomies to it

https://github.com/ThemeFuse/Unyson-Portfolio-Extension/blob/v1.0.6/class-fw-extension-portfolio.php#L18-L19

> what is a best way to provide additional extensions to existing Unyson extension's

[Create your extension](http://manual.unyson.io/en/latest/extensions/create-extension.html#content) as a child extension in theme

```
{theme}/framework-customizations/extensions/portfolio/extensions/YOUR_NAME-portfolio
```

or in [your plugin](http://manual.unyson.io/en/latest/extensions/introduction.html#custom-load-locations)

```
plugins/{your-plugin}/extensions/portfolio/extensions/YOUR_NAME-portfolio
```

----

*Glad that you like it, Thank you*

**Comment by patilswapnilv** [comment]
Thanks a lot; Will work on it and let you know if I need any further help.
