### ISSUE TITLE
Can't add short code to Page Builder

### ISSUE THREAD

**Issue by markcofano** [ThemeFuse/Scratch-Theme#20]
Hello,

I'm following the directions to add a new shortcode to the Page Builder using the "Cookbook Example."

http://manual.unyson.io/en/1.x/extension/shortcodes/index.html#cookbook

i've created the appropriate folders and files per the document 

framework-customizations/
└─theme/
  └─shortcodes/
    └─hr/
      ├─config.php
      └─views/
        └─view.php

using the 1.07 scratch parent theme

The Short Code does not appear in the builder.  I've also created the folders above in the scratch child theme and can't get it work there either.  Please let me know what I am missing.

Thanks!

Mark

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/1600
