### ISSUE TITLE
Got google map alert on Page (backend)

### ISSUE THREAD

**Issue by bnqtoan** [ThemeFuse/Scratch-Theme#22]
I found out the problem with Map Shortcode when it fire an alert on post type which using Unyson page builder

`This page was unable to display a Google Maps element. Please contact the site administrator. If you are the administrator of this site, please check the JavaScript console or check the following page for troubleshooting: http://g.co/mapsJSApiErrors`

For now, I just delete this shortcode as a temporary solution.

Hope that you can fix this problem on next update.

Thank you!

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/1675
