### ISSUE TITLE
Running a SQL query breaks the pages.

### ISSUE THREAD

**Issue by nicolaelitvac** [ThemeFuse/Scratch-Theme#24]
After running a SQL query to update/replace some text with other text in the database, like:
```SQL
update wp_posts set post_content = replace(post_content, 'btn-primary', 'btn-outline-primary');
update wp_postmeta set meta_value = replace(meta_value, 'btn-primary', 'btn-outline-primary');
```

it breaks the pages. The pages are switched to use default editor, and when I'm press the button to use the builder again, everything is lost and I have to build the page again.

Why this is happening?
Is their another way to make this kind of updates without braking the website?

Thanks in advance!

**Comment by ViorelEremia** [comment]
I did that in phpmyadmin and evrything is fine.
