### ISSUE TITLE
[Suggestion] Remove auto-install folder after installing the sample data

### ISSUE THREAD

**Issue by thednp** [ThemeFuse/Scratch-Theme#5]
We don't want to leave the possibility that an end user installs the data again and deletes all his data by mistake :)

**Comment by moldcraft** [comment]
*assigned to @vbarbarosh*

**Comment by vbarbarosh** [comment]
Before Auto Install is done a Full Backup is made. So, if you accidentally made an Auto Install you can roll back the changes.

**Comment by sergiubagrin** [comment]
Hi @thednp, We added a new alert for this case. 

Each time a user click on Install Demo Content a Full Backup is made.
