### ISSUE TITLE
Undefined Variable  other_existing_paths 

### ISSUE THREAD

**Issue by invisiblevision** [ThemeFuse/Scratch-Theme#7]
Hi there thanks for the awsome framework i appreciate your effort , but i am having a small issue using scratch theme , some errors 

Notice: Undefined variable: other_existing_paths in C:\xampp\htdocs\Unyson\wp-content\themes\Scratch-Theme-1.0.3\scratch-parent\framework-customizations\extensions\portfolio\static.php on line 9

Warning: include(): Filename cannot be empty in C:\xampp\htdocs\Unyson\wp-content\themes\Scratch-Theme-1.0.3\scratch-parent\framework-customizations\extensions\portfolio\static.php on line 9

Warning: include(): Failed opening '' for inclusion (include_path='.;C:\xampp\php\PEAR') in C:\xampp\htdocs\Unyson\wp-content\themes\Scratch-Theme-1.0.3\scratch-parent\framework-customizations\extensions\portfolio\static.php on line 9

Thanks

**Comment by moldcraft** [comment]
https://github.com/ThemeFuse/Unyson/issues/414

**Comment by invisiblevision** [comment]
Yaaaraa Namiiiiii ! :+1:  Thanks alot :smiley:
